<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Daftar</name>
   <tag></tag>
   <elementGuidId>565054a1-a22e-4c42-82b4-bc6924822963</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//a[contains(text(),'Daftar')])[3]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.daftar-btn</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>e7f24c42-d245-40a3-9ef8-505934867f9f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>http://vulnqa.cilsy.id/member/signup</value>
      <webElementGuid>f1b94490-1e22-4838-8011-c8a85a578b2a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>daftar-btn</value>
      <webElementGuid>4fed9585-b603-4b40-8fbc-2dd45817a3a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Daftar</value>
      <webElementGuid>2dbeadae-5585-459c-8cad-a35e60562520</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/div[@class=&quot;main-wrapper&quot;]/section[@class=&quot;main-banner&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;row caption-area&quot;]/div[@class=&quot;col-md-12&quot;]/div[@class=&quot;caption&quot;]/div[@class=&quot;inner&quot;]/a[@class=&quot;daftar-btn&quot;]</value>
      <webElementGuid>9e71e2d5-6a09-4279-956d-3899ab9381b6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'Daftar')])[3]</value>
      <webElementGuid>a168a39b-8855-432c-954d-860f4384b208</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Daftar'])[3]/following::a[1]</value>
      <webElementGuid>041a848a-96b1-4772-8f37-b951ca11b48d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Masuk'])[3]/following::a[2]</value>
      <webElementGuid>25a7ea1f-434d-49bf-8f1e-c6bfc35fb2dc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Interaktif'])[1]/preceding::a[1]</value>
      <webElementGuid>67f59680-effc-4de8-bf30-32949228dc1c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Fleksibel'])[1]/preceding::a[1]</value>
      <webElementGuid>3aa616bc-9f23-405c-b9e5-521f2d94ffab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[@href='http://vulnqa.cilsy.id/member/signup'])[4]</value>
      <webElementGuid>2c0dd758-71b8-4a7c-9b81-88a76030047c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/div/div/a</value>
      <webElementGuid>78efaac2-23fe-4adf-aac3-7989d8aa7198</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'http://vulnqa.cilsy.id/member/signup' and (text() = 'Daftar' or . = 'Daftar')]</value>
      <webElementGuid>e2ac8ee0-a98b-41df-83a3-b205e1a4949f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
